### ISSUE TITLE
Create JSON output without $ for text

### ISSUE THREAD

**Issue by jlcheng** [beckchr/staxon#1]
If I want to use staxon to convert xml into JSON then store the result into MongoDB, MongoDB complains that the JSON document have properties that start with "$" the dollar sign. Is there a way to configure staxon to use a character other than $ for text nodes?

**Comment by sakhtar1979** [comment]
Hi,

Can this be made configurable instead via the Builder? Saving it on MongoDB is a relatively important use case and could make this excellent project more invaluable.

**Comment by beckchr** [comment]
Reopening...

Add configuration property to specify element name (other than `$`) used for text content.

**Comment by beckchr** [comment]
The latest from trunk now supports the `textProperty` configuration property.
