### ISSUE TITLE
AutoPrimitiveTarget regex deciding BigDecimal, not String

### ISSUE THREAD

**Issue by DaHarris** [beckchr/staxon#29]
I have a string "493188617199e1170000000000000000" that is being picked up by AutoPrimitiveTarget as a BigDecimal and is crashing the xml converter as a NumberFormatException. It would be great if these exceptions were handled gracefully and fell back to string.

**Comment by beckchr** [comment]
Thank you, makes sense. Just committed a fix, please try it.
