### ISSUE TITLE
exception while handaling array within array

### ISSUE THREAD

**Issue by rajeevaec** [beckchr/staxon#30]
I have a json which contain array with in array element, while using staxon to convert this json to xml. it throws exception that array within array is not handled, can it be possible to create virtual elements within the xml to handle such situation.
sample json:
{
  "customer" : {
    "first-name" : "Jane",
    "phone-number" : [["12", "13"],["14", "15"],"ee"],
	"second-name" : "kumar"
}
}

sample output:

[sample output.txt](https://github.com/beckchr/staxon/files/35227/sample.output.txt)

**Comment by beckchr** [comment]
Sorry... Won't implement.
