### ISSUE TITLE
Issue converting xml to json

### ISSUE THREAD

**Issue by MichaelLoveUSA** [beckchr/staxon#33]
Hi there - I am using the staxon library to convert xml to json and it works fine locally, but when I deploy the service and run from the server I am getting an exception. I suspect it is something different in the environment, but wanted to see if anyone else has experienced the issue. Here is my code:

	public static String xml2jsonObjectWithArrays(String str){
				
        JsonXMLConfig config = new JsonXMLConfigBuilder()
        .autoArray(true)
        .autoPrimitive(true)
        .prettyPrint(false)
        .build();

    	InputStream input = null;
    	OutputStream output = null;
    	String ret = "error";

    	try {
	        input = new ByteArrayInputStream(str.getBytes("UTF-8"));
			output = new ByteArrayOutputStream();
		
	    	/*
	         * Create reader (XML).
	         */
			XMLEventReader reader = XMLInputFactory.newInstance().createXMLEventReader(input);
	
	        /*
	         * Create writer (JSON).
	         */
	        XMLEventWriter writer = new JsonXMLOutputFactory(config).createXMLEventWriter(output);
		
	        /*
	         * Copy events from reader to writer.
	         */
	        writer.add(reader);

It fails on the above call and throws the following exception:

**"Cannot end document"**

Which comes out of here in the source code:

	@Override
	public void writeEndDocument() throws XMLStreamException {
		super.writeEndDocument();
		try {
			if (getScope().getInfo().isArray()) {
				target.endArray();
			}
			target.endObject();
		} catch (IOException e) {
                        throw new XMLStreamException("Cannot end document", e);
		}
		getScope().getInfo().startObjectWritten = false;
	}

Ideas on what may be wrong?

Thanks, Mike

**Comment by beckchr** [comment]
Hard to tell without a concrete XML input causing the issue. Also, the stack trace should show some more information about the root exception (e). This could be anything, including invalid XML or missing write privilege... Doesn't look like a StAXON problem to me. I would recommend to post a question on Stackoverflow.com.
