### ISSUE TITLE
Handling Empty JSON  Array in generated XML

### ISSUE THREAD

**Issue by manjunadigar** [beckchr/staxon#34]
For JSON to XML conversion, if your input JSON is having empty JSONArray  in the converted XML there is  no representation for empty JSON Array.

**Comment by beckchr** [comment]
What do you mean with "input JSON is **having** empty JSONArray"? Can you give an example input, please? Also, what is your configuration like?

**Comment by manjunadigar** [comment]
In the below example there two entries rtc_cm:com.ibm.team.workitem.linktype.relatedworkitem.related and rtc_cm:com.ibm.team.workitem.linktype.schedulePredecessor.predecessor  which have empty JSON Array and on XML Conversion there are no entries for those two  in generated XML.

{"rtc_cm:att.attribute.InvestmentCategory":{"rdf:resource":"https:\/\/win-rfp-fvt-03:9443\/ccm\/oslc\/enumerations\/_-ks74DHyEeaigrPYd-yedw\/att.enum.InvestmentCategory\/att.enum.InvestmentCategory.literal.l1"},"rtc_cm:com.ibm.team.workitem.linktype.relatedworkitem.related":[],"rtc_cm:com.ibm.team.workitem.linktype.schedulePredecessor.predecessor":[]}

**Comment by beckchr** [comment]
This is normal and intended. Array elements are mapped to repeating XML elements. For example,

    {
        "foo": [1, 2]
    }

is mapped to

    <foo>1</foo>
    <foo>2</foo>

Therefore, an empty array results in no elements at all. If you set the `multiplePI` configuration property to `true`, you will get an `<?xml-multiple?>` processing instruction:

    JsonXMLConfig config = new JsonXMLConfigBuilder().multiplePI(true).build();

Now, 

    {
        "foo": []
    }

is mapped to 

    <?xml-multiple foo?>

Hope that helps.
