### ISSUE TITLE
Strange error: Cannot read attribute: element has children or text

### ISSUE THREAD

**Issue by msosic** [beckchr/staxon#35]
I get "ERROR:  'ParseError at [row,col]:[1,33] Cannot read attribute: element has children or text" when I try to convert the following json to xml.

```
{
    "test" : 
    {
        "@TransTyp" : "0",
        "Hdr" : {}
    }
}
```

If I change it a little, everything is fine. These are converted without problem:

```
{
    "test" : 
    {
        "@TransType" : "0",
        "Hdr" : {}
    }
}
```

```
{
    "test" : 
    {
        "@TransTyp" : "0",
        "child" : {}
    }
}
```

Can you help me?

Thanks,
Marko

**Comment by beckchr** [comment]
First input works for me, I get:

    <?xml version='1.0' encoding='UTF-8'?>
    <test TransTyp="0">
        <Hdr/>
    </test>

Can you attach code and input file to show the problem?

**Comment by msosic** [comment]
Sorry, the input json I provided was not correct, because I did some json processing in between. Here is the actual problem.

When I convert the following json, there is no problem.

`{"test":{"@attr":"1", "child":"1"}}`

But when I put child element first and attribute second, I get error. This does not work:

`{"test":{"child":"1", "@attr":"1"}}`

**Comment by beckchr** [comment]
Okay, the input is invalid because objects starting with "@" are interpreted as XML attributes and attributes must come before children or text content ("$"). This is implied by the way the StAX API is designed (all attributes are available after the start element has been read).

**Comment by msosic** [comment]
OK. Thanks. Is there any way not to include 
`<?xml version="1.0"?>`
at the beginning?
