### ISSUE TITLE
PROP_VIRTUAL_ROOT usage

### ISSUE THREAD

**Issue by MichaelLoveUSA** [beckchr/staxon#36]
Is there an example of how to use this property? I do not want the initial xml element in my json output. I have set the value in the config. How do I get it to not write out the root element?

JsonXMLConfig config =
            new JsonXMLConfigBuilder().autoArray(true).autoPrimitive(true).prettyPrint(false).**virtualRoot("Message")**.build();
So, in summary, not an issue, but I would love a little guidance.

**Comment by beckchr** [comment]
Properties are described in the [wiki](https://github.com/beckchr/staxon/wiki/Factory-Configuration). You need to set the name of your root element in the `virtualRoot` property. If you have namespaces, specify the qualified name as described in [`QName.toString()`](https://docs.oracle.com/javase/7/docs/api/javax/xml/namespace/QName.html#toString()).

**Comment by MichaelLoveUSA** [comment]
I got it working. Thanks.
