### ISSUE TITLE
Exception when using a multidimensional array - An array within array

### ISSUE THREAD

**Issue by dhiegoduarte** [beckchr/staxon#40]
While trying to use an json array that contains others arrays, I an getting the error above:

java exception:
java.lang.RuntimeException: Cannot determine next state
  at de.odysseus.staxon.event.SimpleXMLEventReader.hasNext(SimpleXMLEventReader.java:128)

Following a exemple of array that causes the error:
 [["109", "BA8EE75CE7C5D809C1BE189268CD6AB1"],["110","8741663A309138B262F85B40CB2F2FA8"]]

**Comment by beckchr** [comment]
Multidimensional arrays are not supported...

**Comment by dhiegoduarte** [comment]
Thanks.

Regards
Dhiego
