### ISSUE TITLE
duplicate key potential issue with XML to JSON

### ISSUE THREAD

**Issue by plus-** [beckchr/staxon#42]
If we alter the example from the wiki (https://github.com/beckchr/staxon/wiki/Converting-XML-to-JSON) like so:

```
<?xml version="1.0"?>
<customer>
    <first-name>Jane</first-name>
    <last-name>Doe</last-name>
    <phone-number type="work">555-1111</phone-number>
    <address>
        <street>123 A Street</street>
    </address>
    <phone-number type="cell">555-2222</phone-number>
</customer>
```

We end up with the following JSON:

```
{
	"customer": {
		"first-name": "Jane",
		"last-name": "Doe",
		"phone-number": {
			"@type": "work",
			"$": "555-1111"
		},
		"address": {
			"street": "123 A Street"
		},
		"phone-number": {
			"@type": "cell",
			"$": "555-2222"
		}
	}
}
```
Which can cause some errors with some JSON parsers because of the duplicate key. The XML source is valid XML, so I'm not sure how this should be handled as the JSON spec is unclear (https://tools.ietf.org/html/rfc7159 : "The names within an object SHOULD be unique.")

**Comment by beckchr** [comment]
StAXON does not cover that case.
